### PR TITLE
Mark compatibility with angular 16 peer

### PR DESCRIPTION
**Pull request by robertIsaac**
### Checklist

   - Issue number for this PR: #3348
   - Docs included?: yes
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? no it throw weird errors, but I'm sure it's unrelated to my changes

### Description

update peer dependencies to support angular 16

### CODE REVIEW

**Comment by HarryAlvarado28** [comment]
Correct the pipeline to approve the change, it is necessary! 💥🐞

**Comment by robertIsaac** [comment]
> Correct the pipeline to approve the change, it is necessary! 💥🐞

can you explain to me why my changes made the test fails? I tried even on master it's the same locally
can you trigger the pipeline manually for master branch and let me know if it passes or not?

**Comment by wis-dev** [comment]
@robertIsaac you neet to update `.github/workflows/test.yml` file with v16 version.

V15 example 👉🏼 https://github.com/angular/angularfire/pull/3291/files

**Comment by ntherndon97** [comment]
Any updates on this getting fixed to have merged into master so we can update to Angular 16?

**Comment by robertIsaac** [comment]
> @robertIsaac you neet to update `.github/workflows/test.yml` file with v16 version.
> 
> V15 example 👉🏼 https://github.com/angular/angularfire/pull/3291/files

there are many many problems that needs to be fixed, I can't touch the test file before making sure it actually working fine

if it won't be accepted like that, I will have to close it, I tried to fix the build locally, but nothing really work, this repo is too much old and currently it's not working on any node versions, I tried 12, 14, 16, and 18 it always fails with different errors

I can try to upgrade to Angular 16 to make sure it works at node 18 in another PR, but I have no idea how much time and effort it will need, so I can't promise anything

**Comment by robertIsaac** [comment]
this is a nightmare to deal with in windows, nothing has been done in this repo to consider it working on windows, it's unfeasible for me to contribute on the project, so I'm closing the PR

**Comment by nicky-lenaers** [comment]
@robertIsaac Have you tried working with WSL? It may solve your Windows-related issues. I think your contributions are much appreciated!

**Comment by robertIsaac** [comment]
> @robertIsaac Have you tried working with WSL? It may solve your Windows-related issues. I think your contributions are much appreciated!

I tried before, it's a different nightmare
I will just stop trying to contribute to any repo that doesn't support windows

**Comment by jamesdaniels** [comment]
Sorry for the troubles here, we're overdue to clean up the test suite and release a major—the test matrix is getting long in the tooth. We're going to start releasing majors in step with Angular which should really help.

**Comment by robertIsaac** [comment]
> Sorry for the troubles here, we're overdue to clean up the test suite and release a major—the test matrix is getting long in the tooth. We're going to start releasing majors in step with Angular which should really help.

If you are committed to keep the repo compatible with windows, I'd like to help tackle all the issues
I see you already released a version compatible with Angular 16

**Pull request closed without merging**
