### PR TITLE
[messaging] using navigator serviceWorker

### PR DESCRIPTION
**Pull request by hiepxanh**
### Checklist
base on this solution https://github.com/angular/angularfire/issues/1904#issuecomment-635960276
   - Issue number for this PR: #2299 #1904 
   - Docs included?:  no
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### Description
 fixing a bug because `this.angularFireMessaging.messages` not trigger new message any more

### Code sample
nothing changes

### CODE REVIEW

**Comment by hiepxanh** [comment]
@yasinkocak  I just push new code, that pass the Javis Test

**Comment by jamesdaniels** [comment]
It also seems a fix is coming upstream https://github.com/firebase/firebase-js-sdk/pull/3221

**Comment by hiepxanh** [comment]
perfect, I will update my PR once they complete that change @jamesdaniels

**Comment by khaledwalid** [comment]
@hiepxanh , can you send me the right version of @angular/fire and firebasejs from gstatic because i have also the issue that when i'm not receiving an notification

**Comment by hiepxanh** [comment]
`"firebase": "^7.14.5",` and ` "@angular/fire": "^6.0.0",` sir @khaledwalid

**Comment by hiepxanh** [comment]
it is imposible to fix this, some how big problem come from `firebase-messaging-sw.js`
image
some how my browser not update new version, so I try everything I can but still cannot receive notification in forground. Even update the latest `@angular/fire` or `firebase` (newest version with fix is [Fix FCM rxjs Incompatibility
](https://github.com/firebase/firebase-js-sdk/pull/3221))

**Comment by hiepxanh** [comment]
After research, the last `firebase` version auto add the `firebase-messsaging-sw.js` file for me. But when I update the `firebase` in `package.json` the `firebase-messsaging-sw.js` is just not update automaticly with the new version. Solution:
I have to create my own `firebase-messaging-sw.js` that matching to current `firebase version`:
image

**Comment by hiepxanh** [comment]
Close since firebase release new version that fix this bug, I think we need to update the document, because I have serious trouble, the message in `foreground` is not fired if you have missmatch firebase version in `firebase-messaging-sw.js`

**Pull request closed without merging**
