### PR TITLE
fix(firestore): doc and collection methods generic

### PR DESCRIPTION
**Pull request by KingDarBoja**
### Checklist

   - Issue number for this PR: #2504, #2361, #2438
   - Docs included?: **no**
   - Test units included?: **no**
   - In a clean directory, `yarn install`, `yarn test` run successfully? **yes**

### Description

Based on https://github.com/angular/angularfire/issues/2504#issuecomment-655401363, several methods for `AngularFirestoreCollectionGroup`, `AngularFirestoreCollection` and `AngularFirestoreDocument` now uses generics.

Take into account that not every method from the base API (firebase-js) support generics so I had to use the casting at some test specs.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@googlebot I signed it!

**Comment by markgoho** [comment]
@KingDarBoja is there some documentation that we could also update as part of this PR?

**Comment by KingDarBoja** [comment]
Well there is no documentation regarding the use of generics on angularfire methods, so that's why I didn't make one for these changes.

**Comment by jamesdaniels** [comment]
Closing in favor of #2649, I was trying to solve merge conflicts with the web editor. Clearly it was not going well.

**Pull request closed without merging**
