### PR TITLE
Added docs for firebase authentication and firestore Modular V9.

### PR DESCRIPTION
**Pull request by Sapython**
# Added docs for modular firebase authentication, modular firestore documents, and collections.
Added a simple and full-fledged authentication documentation with examples and best practices.
## Added configuration methods and properties for firebase auth.
1. Tenant Id
2. Language Code
3. Auth Persistence
4. Set Local Language

## Added complete docs for accessing and using collections in firebase firestore with full examples
1. docs single time
2. Real-time collection changes
3. Only changes observable
4. Perform simple and compound queries
6. Paginate data
7. Order and limit data

## Features list of document querying
1. Create a document
2. Update a document
3. Delete a document
4. Observer a document for changes
5. Inline querying like
  * Incrementing field value
  * Adding data in an array
  * Removing data from an array
6. Offline data persistence

### Description

This pull request includes documentation for authentication and firestore collections.

### CODE REVIEW

**Comment by lazmeister** [comment]
@jamesdaniels Anyway this could be pushed through? I'm seeing many struggling with a lack of documentation on the new version. Thank you!

**Comment by lazmeister** [comment]
@davideast  Just trying to find owners of the repo to push this through as fast as we can to alleviate issue tickets coming in and help newcomers like me. I know you are all busy and your work is appreciated!

**Comment by jamesdaniels** [comment]
Thanks for this and the energy. 

[We've been working on a new doc structure here,](https://github.com/angular/angularfire/tree/new_docs) I was waiting for the new version to pass the last major in popularity before pushing to modular (rather than compat). We recently hit that milestone, so we'll be rebooting the effort here. If you'd like to start contributing to that branch, we'd welcome it. We'll be aiming to push that to main in the coming weeks.

**Comment by Sapython** [comment]
Ok

**Pull request closed without merging**
