### PR TITLE
Add TDD to the quickstart instructions

### PR DESCRIPTION
**Pull request by PurpleBooth**
It feels a little unfair to leave the user totally on their own to create the tests. Mocking in TypeScript and JavaScript is confusing for beginners (like me), and it's vital to creating a maintainable codebase. This adds a very quickly put together an example of how to develop this example in a TDD style (while hopefully not being distracting).

This is important because quickstarts become the applications of the future, and a bad first impression in testing Angular and Firebase might put them off doing it.

### Checklist

   - Issue number for this PR:  #18
   - Docs included?: yes
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### Description

Some small tweaks to the quickstart that I really wished were there when I was going through it.

### Code sample

Documentation only.

### CODE REVIEW

**Comment by PurpleBooth** [comment]
@googlebot I signed it!

**Comment by PurpleBooth** [comment]
Just FYI, I am pretty new to TypeScript, JavaScript, and Angular so I'd love feedback if this is the right way to create test doubles. 

The main motivation behind this was that the comment to "remember to keep your tests passing" glossed over something that was, while not massively complicated, complicated enough for me to spend an hour or so working out.

**Comment by PurpleBooth** [comment]
I'm guessing there's not an interest in this, going to close this to keep the repo tidy

**Comment by rgant** [comment]
I definitely would be interested in having test setup hints for Angularfire @PurpleBooth. Thank you for the efforts!

**Pull request closed without merging**
