### PR TITLE
feat(schematics): support FIREBASE_TOKEN for `ng deploy`

### PR DESCRIPTION
**Pull request by IKatsuba**
### Checklist

   - Issue number for this PR: #2138 
   - Test units included?: yes 
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### CODE REVIEW

**Comment by IKatsuba** [comment]
Any updates?

**Comment by IKatsuba** [comment]
@jamesdaniels hello! I really need this feature. Can you give comments on it?

**Comment by jamesdaniels** [comment]
We'll get this in shortly, thanks for the contribution.

**Comment by wajeehmisbahkhan** [comment]
Please provide updates on this or at least an alternative on how to use the firebase token in a CI environment. I tried deploying in Github Actions with
```
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```
And I get:
Cannot run login in non-interactive mode. See login:ci to generate a token for use in non-interactive environments.

How do I set the environment variable so that it doesn't require a login?

**Comment by IKatsuba** [comment]
@wajeehmisbahkhan I tried to update the request, but the team never looked at it. Maybe @jamesdaniels  have a different plan. Now I have no time to support this PR.

**Comment by jamesdaniels** [comment]
I can take this to the finish line before I cut 6.1, thanks @IKatsuba

**Comment by IKatsuba** [comment]
@wajeehmisbahkhan you can try this package [@ng-builders/firebase](https://www.npmjs.com/package/@ng-builders/firebase#user-content-ng-buildersfirebasedeploy)

**Pull request merged**
