### PR TITLE
WIP Refactor build process

### PR DESCRIPTION
**Pull request by jamesdaniels**
* Moving to `ng-packagr` to build `@angular/fire`'s package
* Moved the build script over to Typescript and simplified
* Simplified the `angularfire2` wrapper build process
* Testing is done by the Angular CLI
* All specs are now also run under Node
* There's some warnings and dead code trimming happening, I need to double check what's up
* Need to throughly test
* Got some red tests

Builds are some 5x faster now, proper APF, and have non-flattened ES5 and ES2015 targets.

### CODE REVIEW

**Comment by jamesdaniels** [comment]
I might ship as 5.2.2, since this should fix AOT issues...

**Comment by matheo** [comment]
@jamesdaniels please! this is required by our broken builds :(

**Comment by jburson** [comment]
@jamesdaniels Any update on getting this fix out for AOT?  This is preventing our upgrade to angular 8.  Thanks!

**Comment by wiedzmin26** [comment]
@davideast 
Could you review it? Please.........

**Comment by wiedzmin26** [comment]
@jamesdaniels @davideast What's holding from this PR to be merged?

**Comment by jamesdaniels** [comment]
Right now we have some red tests that are concerning me, but unclear if those are flakes. I haven't had a chance to give it a full smoke test. I may put a prerelease on NPM if anyone is interested in helping out.

**Comment by wiedzmin26** [comment]
@jamesdaniels Please do it.

**Comment by troydcthompson** [comment]
Is this dead?

**Comment by hakimio** [comment]
@jamesdaniels so, is the prerelease still coming?

**Comment by jamesdaniels** [comment]
Sorry for the radio silence here. The red tests here have slowed my roll, I'm concerned about breaks; so I'll be targeting this for AngularFire 6 which will be released to officially support Angular 9. 

TBH I've been putting a lot of effort into landing #2187.

**Comment by matheo** [comment]
Thanks @jamesdaniels! Awesome stuff!

**Comment by jamesdaniels** [comment]
Dropping in favor of #2282

**Pull request closed without merging**
