### PR TITLE
Update messaging.md

### PR DESCRIPTION
**Pull request by Tommertom**
I think we all love Angular and if there is an Angular-ish way of using service workers together with this great AngularFire package, it should be noted here. Initially I got really stuck figuring out workbox. While it is very powerfull, but also time consuming. So I recommend giving the reader a bit more comfort about the potential/opportunities using AngularFire.

### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### CODE REVIEW

**Comment by Tommertom** [comment]
@googlebot I signed it!

**Review by jamesdaniels — APPROVED** [review]
Thanks, good change

**Comment by Tommertom** [comment]
@jamesdaniels  I see I made typos.. Sorry about that. You can correct directly or you want me to do a PR? What is most convenient for you...

Two small typos:
- forgot closing . in - 'If you are using the Angular Service Worker, you are not currently able to use AngularFireMessaging out-of-the-box' 
- double this in "Following the discussion in this [this...]

Apologies again.

**Comment by jamesdaniels** [comment]
No worries. Feel free to send a PR.

**Pull request merged**
