### PR TITLE
fix(deploy): deploying with service account

### LINKED ISSUE #3260: Deploy not working with service account in github actions
### Version info

**Angular:** 14.1.0

**AngularFire:** 7.4.1

**Firebase CLI:** Latest being downloaded every time by the actions runner

### How to reproduce these conditions

**Steps to set up and reproduce**

Running the build in a github actions runner with service account exits because the CLI is not signed in

### Expected behavior

The application being built and deployed

### Actual behavior

The deploy command exits before building the app

### PR DESCRIPTION
**Pull request by zal1000**
Deploying with service account was not possible, becouse no checks were made for
GOOGLE_APPLICATION_CREDENTIALS env variable

Fixes #3260

### Checklist

   - Issue number for this PR: #3260
   - Docs included?: no
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? yes

### Description

Not trying to log into firebase CLI when `GOOGLE_APPLICATION_CREDENTIALS` are detected.
Doing that allows the deploy job to run in an automated env with a service account only

### CODE REVIEW

**Comment by jamesdaniels** [comment]
Thanks for the fix, I'll look at merging this in for a patch release ASAP

**Comment by Kunal-Deshpande** [comment]
Hi,
Do we have any update merging this MR?
Firebase is deprecating the FIREBASE_TOKEN env variable for authentication. So need to authenticate using the service account.
It would be good if the application picked up the GOOGLE_APPLICATION_CREDENTIALS  env variable.

**Comment by HmFlashy** [comment]
Is there any update on this matter? thanks

**Comment by gavinsawyer** [comment]
Waiting on this for my project, was losing my mind finding out what was wrong.

**Comment by gavinsawyer** [comment]
This is working in @angular/fire@7.6.1 & firebase-tools@12.3.0:

1. Add an auth step to your GitHub Actions yaml file using the secret generated by `% firebase init hosting:github`; reference the output for the FIREBASE_TOKEN env variable:
```yaml
- id:   auth
  uses: google-github-actions/auth@v1
  with:
    credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_XYZ }}
    token_format: access_token
- run:  ng deploy
  env:
    FIREBASE_TOKEN: ${{ steps.auth.outputs.access_token }}
```
2. Add `gha-creds-*.json` to your .gitignore file.
3. In [IAM & Admin](https://console.cloud.google.com/iam-admin/iam), grant `Service Account Token Creator` to the GitHub Actions principal:

Screenshot 2023-06-03 at 21 36 07

**Review by davideast — APPROVED** [review]
@zal1000 Thank you so much and a very serious apology for the late review.

**Pull request closed without merging**
