### PR TITLE
add eslint

### PR DESCRIPTION
**Pull request by robertIsaac**
### Checklist

   - Issue number for this PR: NA
   - Docs included?: no
   - Test units included?: no
   - In a clean directory, `yarn install`, `yarn test` run successfully? no

### Description

adding initial `eslint` and fixing the current errors

### CODE REVIEW

**Comment by robertIsaac** [comment]
something is wrong in the pipeline, it report lint errors that don't exist
the reported file don't have any anywhere in it

**Review by davideast — APPROVED** [review]
@robertIsaac I can not thank you enough for this!

**Comment by robertIsaac** [comment]
> @robertIsaac I can not thank you enough for this!

I'm really happy to see it merged :)

**Comment by robertIsaac** [comment]
@davideast I can also add prettier and eslint prettier plugin, if that's something you'd like to have in the project

**Pull request merged**
