### PR TITLE
WIP: AngularFire Guide

### PR DESCRIPTION
**Pull request by davideast**
## A docs site!

We are working on an early stage docs site! There's lots of things left to fix, but it has most of the existing documentation and in a format that's easier to navigate. 

[Early Preview](https://afdocsite--wip-n6vieb7x.web.app/)

### Stage 1

- [x] Set up basic responsive layout 
- [x] Migrate content from `docs/` to `site/` 

### Stage 2

*Wont be addressed with this PR*

- [ ] Fix text sizing and spacing issues
- [ ] Break apart CSS files from the mega CSS file
- [ ] Update old documentation
- [ ] Set up Preview Channels for easy collaboration

### Stage 3

*Wont be addressed with this PR*

- [ ] Add a snazzy landing page!
- [ ] Expand documentation sections
- [ ] Add recipes/tutorials

### CODE REVIEW

**Review by jamesdaniels — APPROVED** [review]
LGTM

**Comment by jamesdaniels** [comment]
Great start.

**Comment by jamesdaniels** [comment]
@davideast Nit. Make sure your .gitignore is ignoring caches and generated assets.

**Comment by davideast** [comment]
> @davideast Nit. Make sure your .gitignore is ignoring caches and generated assets.

I want to try seeing what affect having the `.firebase` cache in source has for deployments. As the site grows I think it can help. If it janks things up I'll remove it.

**Pull request merged**
