### PR TITLE
Updated id to $id

### PR DESCRIPTION
**Pull request by odenman250**
"FirebaseDeploySchema" schema is using the keyword "id" which its support is deprecated. Now using "$id" for schema ID.

### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### CODE REVIEW

**Comment by jamesdaniels** [comment]
Thanks for the contribution, we won't be able to merge until the next major release as this would break older versions of Angular that we support.

**Comment by odenman250** [comment]
Thanks sorry I realised that after committing.

**Comment by KingDarBoja** [comment]
This is fixed by latest minor release, right?

**Comment by jamesdaniels** [comment]
I did not remove "id" (as this PR does) but added "$id" in 6.1.5 @KingDarBoja. I would consider this for inclusion in 7.0 which i just released the first alpha of.

**Review by jamesdaniels — APPROVED** [review]

**Pull request merged**
