### PR TITLE
Fix angular 10 style moduleWithProviders

### PR DESCRIPTION
**Pull request by yasinkocak**
### Checklist

   - Issue number for this PR: #2526 

### Description

Generic typing ModuleWithProviders<T>

### CODE REVIEW

**Comment by shadow1349** [comment]
+1 this is a big blocker for Angular 10 upgrade

**Comment by DominikDitoIvosevic** [comment]
Where can we track the travis queue and progress? Can we get this in now? It's a blocker

**Comment by yasinkocak** [comment]
https://travis-ci.community/t/travis-ci-branch-expected-waiting-for-status-to-be-reported/829

**Comment by yasinkocak** [comment]
@jamesdaniels is there any action i should do for travis-ci?

**Comment by shadow1349** [comment]
Looks like this is all good, can we get this merged please?

**Comment by fritzschoff** [comment]
For the love of god, just merge it!

**Comment by jamesdaniels** [comment]
Hey all, sorry about the delay here. I'd been taking some vacation and just getting back to 6.0 patches this week.

**Comment by marzecm** [comment]
Any idea about new release date? Many thanks ;)

**Comment by shadow1349** [comment]
@marzecm If you want to use it right away you can use the canary build which I've been using.

**Pull request merged**
