### PR TITLE
feat(firestore): options to include document ID on valueChanges()

### PR DESCRIPTION
**Pull request by mjastrzebowski**
### Checklist

   - Issue number for this PR: #2109 
   - Docs included?: **Yes** 
   - Test units included?: **Yes** 
   - In a clean directory, `yarn install`, `yarn test` run successfully? **Yes**

### Description

Continuation of #1976 - added `idField` option for `document.valuChanges()` to include the document ID on the emitted data payload. Updated documentation for this one and added some missing changes from the previous PR. 

### Code sample
```js
documentRef.valueChanges({ idField: 'customID' }).subscribe()
// emits [ { customID: 'MrfFpRBfWLTd7LqiTt9u', ...data }, ... ]
```

### CODE REVIEW

**Comment by leolara** [comment]
This is very important feature, thank you

**Comment by leolara** [comment]
I think this does not work if you call it on a collection instead of a document

**Comment by leolara** [comment]
This is what I had to do to make it work on a collection. Perhaps there is better way, but this is my first week with rxjs:

```
readAll(): Observable<Listing[]> {
        return this.afs.collection<Listing>(COLLECTION_NAME).snapshotChanges().pipe(
            map((payloads) => {
                return payloads.map(({payload}) => {
                    return {
                        // tslint:disable-next-line:ban-types
                        ...payload.doc.data() as Object,
                        ...{id: payload.doc.id}
                    } as Listing;
                });
            })
        );
    }
```

**Comment by EdricChan03** [comment]
> LGTM, thanks! Will merge once ready to cut 5.3

Are there any updates to this PR? It's been a while since release 5.3.

**Comment by jamesdaniels** [comment]
Whoops, meant to get this into 5.3 but working on 6 ate up all my time. Will get this into 6.1.

**Comment by kyleabens** [comment]
Can this be added to 6.0.4?

**Comment by jamesdaniels** [comment]
New API so had to wait for a minor, will aim to get this in today for `rc.1`.

**Pull request merged**
