### PR TITLE
Marking peer support for NG12

### PR DESCRIPTION
**Pull request by jamesdaniels**
Mostly just build process and testing stuff.

#2832, #2830, #2829

### CODE REVIEW

**Comment by johanchouquet** [comment]
Hi @jamesdaniels , I saw that you commented line 18 of server.ts `import 'dir-loader!./firestore-protos';`.
I added this line myself to deal with the protos for firebase dependencies on the server. But with ng12 and webpack 5 under the hood, I've been struggling quite much with protos stuff. I tried to remove just like you this line with `dir-loader`, but I encounter other errors (also tried the `externalDependencies` in `angular.json`). But none of this works for me.

Do you have some clues on how to replace the dir-loader thing with Angular 12 which supports webpack 5 (related to Assets modules?). I don't have any `webpack.config.js`.

**Comment by jamesdaniels** [comment]
> Hi @jamesdaniels , I saw that you commented line 18 of server.ts `import 'dir-loader!./firestore-protos';`.
> I added this line myself to deal with the protos for firebase dependencies on the server. But with ng12 and webpack 5 under the hood, I've been struggling quite much with protos stuff. I tried to remove just like you this line with `dir-loader`, but I encounter other errors (also tried the `externalDependencies` in `angular.json`). But none of this works for me.
> 
> Do you have some clues on how to replace the dir-loader thing with Angular 12 which supports webpack 5 (related to Assets modules?). I don't have any `webpack.config.js`.

I made an alternative now that we can't lean on dir-loader, `import '@angular/fire/firestore-protos';`

**Comment by johanchouquet** [comment]
Hi @jamesdaniels,

Thanks for coming back to me. Sure thing, I'll try that. But, just to be clear, I suppose it is only in the v7 of AngularFire, right ? Or is it ported back into v6.1.5 ?

**Comment by jamesdaniels** [comment]
@johanchouquet I did not port backwards no. One could use a similar strategy though, see my build script for its construction if your not ready for the upgrade.

**Comment by johanchouquet** [comment]
Sure thing, I'll check it out. Thanks @jamesdaniels.

**Pull request merged**
