### PR TITLE
added env FIREBASE_TOKEN to deploy at CI/CD

### PR DESCRIPTION
**Pull request by yasinkocak**
### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### Description
Allow to use `env` `FIREBASE_TOKEN` while deploying on CI/CD

### CODE REVIEW

**Comment by yasinkocak** [comment]
@googlebot I signed it!

**Comment by yasinkocak** [comment]
issue #2523

**Comment by alessio-libardi** [comment]
Please someone review this PR.

**Comment by ammaarpatel99** [comment]
Just wondering if there is any progress on this

**Comment by YogliB** [comment]
anyone reviewing this?

**Review by jonasdebeukelaer — APPROVED** [review]

**Comment by jamesdaniels** [comment]
Sorry for this being slow, API additions have to wait until the next minor release is planned. 6.1 is dropping shortly. There's already a PR here #2327 that I'm aiming to pull in.

**Pull request closed without merging**
