### PR TITLE
feat(functions): Add options param to httpsCallable functions

### PR DESCRIPTION
**Pull request by NothingEverHappens**
see #2433

I don't see a good way to test it without a big refactoring, open to suggestions.

### CODE REVIEW

**Comment by wiedzmin26** [comment]
@NothingEverHappens maybe use emulator?
https://firebase.google.com/docs/emulator-suite

**Comment by pdemilly** [comment]
why wait. Without that change cloudFunctions are not usable. The limit of 60s to execute a cloud function when you know how slow firestore queries are make this impossible to use. At least increase that limit to the highest value possible and let the cloud function handle the timeout

**Comment by majid701** [comment]
I really need this. Any idea on when this is going to be merged?

**Comment by mcarriere** [comment]
Can we expect this in the near future?

**Comment by davemake** [comment]
Angular is nothing but problems!

**Review by mcarriere — APPROVED** [review]

**Pull request merged**
