### PR TITLE
fix: fixes generic type exception in firestore interfaces: (#3290)

### PR DESCRIPTION
**Pull request by eyoeldefare**
fixes issue #3290. Its complaining because some of the interfaces are not extended with the expected generic type T when they're expecting a type of T.

### Checklist

   - Issue number for this PR: #nnn (required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### CODE REVIEW

**Review by BoltzBit — COMMENTED** [review]
Hey!! don't forget to add a reviwer!

**Review by BoltzBit — APPROVED** [review]

**Comment by Dyllanjrusher** [comment]
Hey, Thanks for your contribution! It looks like you haven't added a reviewer with write access. Can you do so to get this in? It looks like the issue is still holding quite a few folks up, including myself. I'll check in in a few days but will unfortunately have to resubmit your changes if this doesn't get in soon.

**Comment by vytautas-pranskunas-** [comment]
watching

**Review by JSponaugle — APPROVED** [review]
Exactly What is required to fix this issue

**Review by GerardoTovar — APPROVED** [review]

**Review by drewzh — APPROVED** [review]

**Comment by drewzh** [comment]
Just to note to anyone watching - this only seems to apply to the compat layer. If using the new syntax (which rather annoyingly doesn't seem to be well documented), you won't face this issue. At least this is my experience having had the issue and then subsequently refactoring to remove /compat/ layers and fixing the issue as a result.

**Review by afspear — APPROVED** [review]

**Review by tsanhan — APPROVED** [review]

**Review by pbrennand-francis — APPROVED** [review]

**Comment by pbrennand-francis** [comment]
Who has write access who can approve this as a reviewer? Seems to be a simple fix to something affecting a number of people.

**Review by ingoscardan — APPROVED** [review]

**Review by davideast — APPROVED** [review]
@eyoeldefare Thank you so much for this contribution and apologies for the last response from us. I'm working on cleaning up this repository. There have been a ton of PRs submitted to address this issue so I'm going through them all now and I'm not currently sure which one will get submitted due to the constant running of the CI processes but I promise it will get fixed!

**Pull request merged**
