### PR TITLE
fix: exception while running command ng deploy (#2088)

### LINKED ISSUE #2088: Exception while running command: ng run x:deploy
### Version info

**Angular:** 8.0.0

**Firebase:** 6.1.0

**AngularFire:** 5.2.0-rc.1

**OS:** Windows 10 Pro (Version: 1809)

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

### Debug output

**Errors in the JavaScript console**

```
C:\Users\X\Documents\X\X\X>ng run Admin:deploy
ENOENT: no such file or directory, open '\C\Users\X\Documents\X\X\X\.firebaserc'
Error: ENOENT: no such file or directory, open '\C\Users\X\Documents\X\X\X\.firebaserc'
    at Object.openSync (fs.js:431:3)
    at Object.readFileSync (fs.js:333:35)
    at Object.getFirebaseProjectName (C:\Users\X\Documents\X\X\X\node_modules\@angular\fire\schematics\utils.js:53:41)
    at Object.<anonymous> (C:\Users\X\Documents\X\X\X\node_modules\@angular\fire\schematics\deploy\builder.js:26:37)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\X\Documents\X\X\X\node_modules\@angular\fire\schematics\deploy\builder.js:4:58)
```

**Output from `firebase.database().enableLogging(true);`**

**Screenshots**

### Expected behavior

Running the following command `ng run x:deploy` have to successfully build and deploy the project to Firebase Hosting.

**Note:** the `x` above is the project name.

### Actual behavior

Fails at the beginning to find `.firebaserc` file but it exists. I figured out the path `\C\Users\X\Documents\X\X\X\.firebaserc` is wrong.

### PR DESCRIPTION
**Pull request by ngdevelop-tech**
### Checklist

   - Issue number for this PR: #2088(required)
   - Docs included?: (yes/no; required for all API/functional changes) 
   - Test units included?: (yes/no; required) 
   - In a clean directory, `yarn install`, `yarn test` run successfully? (yes/no; required)

### Description

When we execute `ng deploy` command, `workspace.root` gives the wrong path in the Windows environment, that's why it doesn't work in the Windows environment.
Using only `project root` In `getFirebaseProjectName` and `deploy`, will successfully allow `ng deploy` while executing it at project root in windows and linux environment.
fixes #2088

### CODE REVIEW

**Comment by ngdevelop-tech** [comment]
@NothingEverHappens, Thanks for the approval.
Please help me, What should I do further to resolve failed build?
Do I need to merge the `master` branch again? , 
In `Logs` it is showing one log for version mismatch.

**Comment by NothingEverHappens** [comment]
@ngdevelop-tech 
My understanding is that this is a build issue, and not PR issue, but I didn't look very deep, 
I'm going to take a closer look next week.

Meanwhile you can try running `./node_modules/.bin/karma start --single-run --browsers ChromeHeadlessTravis --reporters mocha &&
yarn test:node &&
node tools/run-typings-test.js &&
bash ./test/ng-build/build.sh"` on your machine to verify that it works locally

**Comment by Splaktar** [comment]
Is this PR no longer needed now that PR https://github.com/angular/angularfire/pull/2279 has been merged to fix https://github.com/angular/angularfire/issues/2088?

**Comment by ngdevelop-tech** [comment]
@Splaktar because PR #2279 has been merged and closes the #2088, closing this PR.

**Pull request closed without merging**
